config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :homes do
    resources :bookings, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create, :index ]
  end

  resources :reviews, only: [ :show, :edit, :update, :destroy ]

  resources :bookings, only: [:index, :show, :destroy, :update]

  resources :listings, only: [:index]

  resources :guests, only: [:index]

  resources :users, only: [:show, :update, :edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :home
  belongs_to :user

  validates :check_in, presence: true
  validates :check_out, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
  mount_uploader :photo, PhotoUploader

  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :home
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :homes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password photo photo_cache first_name last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email password photo photo_cache first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @home = Home.find(params[:home_id])
    @booking = Booking.new(booking_params)
    @booking.home = @home
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      redirect_to home_path(@home)
    end
  end

  def show
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @homes = Home.all.where.not(user_id: current_user)
    @markers = @homes.map do |home|
      {
        lat: home.latitude,
        lng: home.longitude,
        infoWindow: { content: render_to_string(partial: "/homes/info_window", locals: { home: home }) }
      }
    end
  end

  def show
    @booking = Booking.new
    @markers = [{
      lat: @home.latitude,
      lng: @home.longitude,
      infoWindow: { content: render_to_string(partial: "/homes/info_window", locals: { home: @home }) }
    }]
  end

  def new
    @home = Home.new
    @home.user = current_user
  end

  def create
    @home = Home.new(home_params)
    @home.user = current_user
    if @home.save
      redirect_to home_path(@home)
    else
      @home = Home.new(home_params)
      redirect_to new_home_path
    end
  end

  def edit
  end

  def update
    @home.update(home_params)

    redirect_to home_path(@home)
  end

  def destroy
    @home.destroy

    redirect_to user_path(@home.user_id)
  end

  private

  def home_params
    params.require(:home).permit(:name, :address, :photo, :home_type, :guest, :bedroom, :bed, :bath, :rate, :description)
  end

  def set_home
    @home = Home.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @home = Home.find(params[:home_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @home = Home.find(params[:home_id])
    @review.home = @home
    @review.user = current_user
    @review.save
    redirect_to home_path(@home)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show]
  skip_before_action :authenticate_user!, only: [:show]

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to
  end

  def show
    if current_user
      @upcoming_bookings = Booking.select do |booking|
        booking.home.user_id == current_user.id
      end
      @bookings = Booking.select do |booking|
        booking.user_id == current_user.id
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :photo, :first_name, :last_name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-4" style="padding:60px">
      <%= simple_form_for [@home] do |f| %>
        <%= f.input :home_type, placeholder: 'Entire House' %>
        <%= f.input :name, maxlength: 30, placeholder: 'Beautiful Downtown Location', opacity: 3%>
        <%= f.input :address, placeholder: '20 W 34th St, New York, NY 10001, USA'%>
        <%= f.input :guest, :collection => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
        <%= f.input :bedroom, :collection => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
        <%= f.input :bed, :collection => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
        <%= f.input :bath, :collection => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] %>
        <%= f.input :rate, placeholder: '$25' %>
        <%= f.input :description, placeholder: 'A gorgeous location right in the heart of downtown New York with two....' %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, 'List this house', class: 'btn btn-primary'%>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/_info_window.html.erb
<div class="card" style="width: 10rem;">
  <%= cl_image_tag home.photo, class: 'card-img' %>
  <div class="card-body">
    <h6 class="card-title"><%= home.name %></h6>
    <small class="card-text"><%= home.address %></small>
    <%= link_to 'check it out', home_path(home) %>
  </div>
</div>

app/views/homes/_show_guest.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col border-bottom">
      <h4 class="text-muted"><%= @home.home_type %></h4>
      <h2><%= @home.name %></h2>
      <p><%= @home.address %></p>
      <p><%= @home.bedroom %> Bedrooms</p>
      <p><i class="fas fa-user"></i> <%= @home.guest %> - <i class="fas fa-bed"></i> <%= @home.bed %> - <i class="fas fa-toilet"></i> <%= @home.bath %></p>
      <br>
      <br>
      <div
        class="rounded shadow show-map"
        id="map"
        style="width: 220px;
        height: 200px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
    <div class="col">
      <div class="details-show">
        <%= link_to user_path(@home.user.id), class: 'text-decoration-none' do %>
          <div class="text">
            <%= cl_image_tag(@home.user.photo, alt: "avatar", class: "card-user avatar") %> <%= @home.user.first_name.capitalize %>
          </div>
        <% end %>
      </div>
      <%= cl_image_tag @home.photo, class: "img-thumbnail show-image" %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <br>
      <p class="border-bottom details-show"><%= @home.description %></p>
      <br>
      <div>
        <div class="details-show">
          <h3>Reviews</h3>
          <%= link_to 'leave a review', new_home_review_path(@home.id) %>
          <% review_count = 0 %>
          <% @home.reviews.each do |review| %>
            <% review_count += 1 %>
          <% end %>
          <% total = 0.0 %>
          <% @home.reviews.each do |review| %>
            <% total += review.rating %>
          <% end %>
          <% if total != 0 %>
            <i class="fas fa-star"></i>
              <% final = total/review_count %>
              <%= final.round(2) %>
          <% else %>
            <i class="fas fa-star"></i> <%= total %>
          <% end %>
          <small>
          (<%= review_count %> reviews)
          </small>
        </div>
        <div class="col overflow-auto listings">
          <% @home.reviews.each do|review| %>
            <div class="list-group border-bottom review-list">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">
                  <%= link_to user_path(review.user.id), class: 'text-decoration-none' do %>
                    <div class="text">
                      <%= cl_image_tag(review.user.photo, class: "card-user avatar") %>
                      <%= review.user.first_name.capitalize %>
                    </div>
                  <% end %>
                </h5>
                <small>
                  <%= review.created_at.to_date.to_s(:long)  %>
                </small>
              </div>
              <p class="mb-1">
                "<%= review.content %>"
              </p>
              <small>
                <i class="fas fa-star"></i> <%= review.rating %>
              </small>
              <br>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="create-form m-3 booking-form">
        <p>
          $<%= @home.rate %> /per night
        </p>
        <%= simple_form_for [@home, @booking] do |f| %>
          <%= f.input :check_in %>
          <%= f.input :check_out %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal"><%= f.button :submit, 'Book this home', class: 'btn btn-primary'%></button>
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Congratulations!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  you have booked <%= @home.name %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/_show_host.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col border-bottom">
      <h3 class="text-muted"><%= @home.home_type %></h3>
      <h2><%= @home.name %></h2>
      <p><%= @home.address %></p>
      <p><%= @home.bedroom %> Bedrooms</p>
      <p><i class="fas fa-user"></i> <%= @home.guest %> - <i class="fas fa-bed"></i> <%= @home.bed %> - <i class="fas fa-toilet"></i> <%= @home.bath %></p>
      <br>
      <br>
      <div
        class="rounded shadow show-map"
        id="map"
        style="width: 220px;
        height: 200px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
    <div class="col">
      <div class="details-show">
        <%= link_to user_path(@home.user.id), class: 'text-decoration-none' do %>
          <div class="text">
            <%= cl_image_tag(@home.user.photo, alt: "avatar", class: "card-user avatar") %> <%= @home.user.first_name.capitalize %>
          </div>
        <% end %>
      </div>
      <%= cl_image_tag @home.photo, class: "img-thumbnail show-image" %>
    </div>
    <div class="w-100"></div>
    <div class="col">
      <br>
      <p class="border-bottom details-show"><%= @home.description %></p>
      <br>
      <div>
        <div class="details-show">
          <h3>Reviews</h3>
          <% review_count = 0 %>
          <% @home.reviews.each do |review| %>
            <% review_count += 1 %>
          <% end %>
          <% total = 0.0 %>
          <% @home.reviews.each do |review| %>
            <% total += review.rating %>
          <% end %>
          <% if total != 0 %>
            <i class="fas fa-star"></i>
              <% final = total/review_count %>
              <%= final.round(2) %>
          <% else %>
            <i class="fas fa-star"></i> <%= total %>
          <% end %>
          <small>
          (<%= review_count %> reviews)
          </small>
        </div>
        <div class="col overflow-auto listings">
          <% @home.reviews.each do|review| %>
            <div class="list-group border-bottom review-list">
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">
                  <%= link_to user_path(review.user.id), class: 'text-decoration-none' do %>
                    <div class="text">
                      <%= cl_image_tag(review.user.photo, class: "card-user avatar") %>
                      <%= review.user.first_name.capitalize %>
                    </div>
                  <% end %>
                </h5>
                <small>
                  <%= review.created_at.to_date.to_s(:long)  %>
                </small>
              </div>
              <p class="mb-1">
                "<%= review.content %>"
              </p>
              <small>
                <i class="fas fa-star"></i> <%= review.rating %>
              </small>
              <br>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="create-form m-3">
        <p>$<%= @home.rate %> per night</p>
        <%= link_to 'Edit Listing', edit_home_path(@home), class:'btn btn-warning m-1' %>
        <%= link_to 'Delete', home_path(params[:id]), method: :delete, class:'btn btn-danger m-1' %>
      </div>
    </div>
  </div>
</div>

app/views/homes/edit.html.erb
<%= render 'form', home: @home %>

app/views/homes/index.html.erb
<div class="d-flex justify-content-around">
  <div class="shadow p-4 mb-5 bg-white rounded overflow-auto main-list">
    <% @homes.each do |home| %>
      <%= link_to home_path(home), class: "text-decoration-none text" do %>
        <div class="index-card card mb-3 p-2 shadow-sm">
          <div class="row no-gutter linkable">
            <div class="col-md-4 img-card">
              <%= cl_image_tag home.photo, class: "card-img" %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <p class="card-text"><small class="text-muted"><%= home.home_type %></small></p>
                <h5 class="card-title"><%= home.name %></h5>
                <p class="card-text"><%= home.address %></p>
                <p class="card-text"><small class="text-muted"><%= home.guest %> guests - <%= home.bedroom %> bedrooms - <%= home.bed %> beds - <%= home.bath %> baths - $<%= home.rate %> per night</small></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="shadow p-3 mb-5 bg-white rounded">
    <div
      class="rounded index-map"
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

app/views/homes/new.html.erb
<%= render 'form', home: @home %>

app/views/homes/show.html.erb
<% if current_user == nil || current_user.id != @home.user_id%>
  <%= render 'show_guest' %>
<% else %>
  <%= render 'show_host' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home Away</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path("https://www.farmers.com/content/dam/farmers/marketing/digital/aem/icons/misc/icon-home.svg") %>

  </head>
  <body>
    <p class="alert"><%= alert %></p>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='home d-flex flex-column justify-content-around align-items-center'>
  <div class="first-section">
    <h1 class='text-center text-white title'>
      Home Away
    </h1>
    <h3 class='text-center text-white mt-3 description'>Search for homes all over the world!</h3>
    <div class="text-white rounded d-flex justify-content-center">
      <% if current_user.nil? %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary mt-3 toilet-button' %>
      <% else %>
        <%= link_to "search", homes_path, class: 'btn btn-primary mt-3 toilet-button' %>
      <% end %>
    </div>
    <div class="text-white rounded d-flex justify-content-center">
      <% if current_user.nil? %>
        <%= link_to "Demo", homes_path, class: 'btn btn-primary mt-3 toilet-button' %>
      <% end %>
    </div>
  </div>
</div>
  <div class='container'>
    <div class="cards row d-flex justify-content-around center-items">
      <div class="card shadow p-3 bg-white rounded" style="width: 18rem;">
          <%= image_tag ("sign.jpg"), class:'card-img-top' %>
        <div class="card-body">
          <h4>Sign up.</h4>
          <p class="card-text">Quickly sign up to Home Away with our seemless sign-up and be connected to millions of homes instantly.</p>
        </div>
      </div>
      <div class="card shadow p-3 bg-white rounded" style="width: 18rem;">
        <%= image_tag ("beach-house.jpg"), class:'card-img-top' %>
        <div class="card-body">
          <h4>Find a home.</h4>
          <p class="card-text">Find homes in your area with a simple click of a button and begin your journey with Home Away.</p>
        </div>
      </div>
      <div class="card shadow p-3 bg-white rounded" style="width: 18rem;">
        <%= image_tag ("enjoy.jpg"), class:'card-img-top' %>
        <div class="card-body">
          <h4>Enjoy with friends.</h4>
          <p class="card-text">Open your favorite app and enjoy traveling to some of the best homes in the world.</p>
        </div>
      </div>
    </div>
  </div>

  <div class='container bottom-card'>
    <div class="card shadow p-3 mb-3" style="max-width: 100rem;">
      <div class="card-header text-center">About Us</div>
        <div class="card-body text-dark">
          <p class="card-text text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </div>
    </div>
  </div>

app/views/reviews/new.html.erb
<div class="container devise-form">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-4">
      <%= simple_form_for [@home, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating %>
        <%= f.submit "add a review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_booking_form.html.erb
<%= simple_form_for [@home, @booking] do |f| %>
  <%= f.input :check_in %>
  <%= f.input :check_out %>
  <%= f.button :submit, 'Book this home', class: 'btn btn-primary'%>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://www.farmers.com/content/dam/farmers/marketing/digital/aem/icons/misc/icon-home.svg" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Search", homes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "List Home", new_home_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_show_host.html.erb
<div>
  <h1 class="profile">My Profile</h1>
<div class="container d-flex">
  <div class="profile-container-host">
    <div class='profile-card card-padding shadow'>
      <div class="profile-picture">
        <%= cl_image_tag current_user.photo, class: 'avatar-large' %>
      </div>
      <div class='border-bottom card-padding'>
        <%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %>
      </div>
      <div class='border-bottom card-padding'>
        <div>Joined in <b><%= @user.created_at.to_s.match(/^\d+/) %></b>
        </div>
      </div>
      <div class='border-bottom card-padding'>
        <div>
          <i class="fas fa-comment-alt"></i>
          <% review_count = 0 %>
          <% @user.homes.each do |home| %>
             <% review_count += home.reviews.all.count %>
          <% end %>
          <%= review_count %>
          Reviews
        </div>
        <div>
          <% total = 0.0 %>
          <% @user.homes.each do|home| %>
            <% home.reviews.each do |review| %>
              <% total += review.rating %>
            <% end %>
          <% end %>
          <% if total != 0 %>
            <i class="fas fa-star"></i>
              <% final = total/review_count.round %>
              <%= final.round(2) %>
                stars
          <% else %>
            <i class="fas fa-star"></i> <%= total %> Stars
          <% end %>
        </div>
      </div>
      <div class="card-padding-edit">
        <%= link_to 'Edit Name', edit_user_path(current_user), class:'btn btn-primary' %>
      </div>
      <div class="card-padding">
        <%= link_to 'Change Password', edit_user_registration_path(current_user), class:'btn btn-primary' %>
      </div>
    </div>
  </div>
  <div class="about-me-container">
    <div>
      <h4 class="reviews">Listings</h4>
    </div>
    <div class="three-listings overflow-auto shadow">
      <div class="list-group list-group-horizontal">
        <% @user.homes.each do |home| %>
          <%= link_to home_path(home), class: 'text-decoration-none' do %>
            <div class="card card-padding card-listing shadow-sm">
              <%= cl_image_tag home.photo, class: 'card-img-top rounded card-picture' %>
              <div class="card-body body">
                <p class="card-text text"><%= home.name %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <h4 class="reviews">Upcoming Guests</h4>
    </div>
    <div class="three-listings overflow-auto shadow">
      <div class="list-group list-group-horizontal">
        <% @upcoming_bookings.each do |booking| %>
          <%= link_to home_path(booking.home), class: 'text-decoration-none' do  %>
            <div class="card card-padding card-listing shadow-sm">
              <%= cl_image_tag booking.home.photo, class: 'card-img-top rounded card-picture' %>
              <div class="card-body">
                <p class="card-text text">
                  <%= booking.home.name %>
                </p>
                <small class="text">
                  <%= booking.check_in.to_date.to_s(:long) %> -
                </small>
                <small class="text">
                  <%= booking.check_out.to_date.to_s(:long) %>
                </small>
                <div>
                  <%= link_to user_path(booking.user.id) do  %>
                  <%= cl_image_tag(booking.user.photo, class: "card-user avatar")%>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <h4 class="reviews">Bookings</h4>
    </div>
    <div class="three-listings overflow-auto shadow">
      <div class="list-group list-group-horizontal">
        <% @bookings.each do |booking| %>
          <%= link_to home_path(booking.home), class: 'text-decoration-none' do  %>
            <div class="card card-padding card-listing shadow-sm">
              <%= cl_image_tag booking.home.photo, class: 'card-img-top rounded card-picture' %>
              <div class="card-body">
                <p class="card-text text">
                  <%= booking.home.name %>
                </p>
                <small class="text">
                  <%= booking.check_in.to_date.to_s(:long) %> -
                </small>
                <small class="text">
                  <%= booking.check_out.to_date.to_s(:long) %>
                </small>
                <div>
                  <%= link_to user_path(booking.user.id) do  %>
                  <%= cl_image_tag(booking.user.photo, class: "card-user avatar")%>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div>
      <h4 class="reviews">Reviews</h4>
    </div>
    <div class="container d-flex review-container">
      <div class="row shadow">
        <div class="col overflow-auto listings">
          <% @user.homes.each do|home| %>
            <% home.reviews.each do |review| %>
              <div class="list-group border-bottom review-list">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">
                    <%= link_to user_path(review.user.id), class: 'text-decoration-none' do %>
                      <div class="text">
                        <%= cl_image_tag(review.user.photo, class: "card-user avatar") %>
                        <%= review.user.first_name.capitalize %>
                      </div>
                    <% end %>
                  </h5>
                  <small>
                    <%= review.created_at.to_date.to_s(:long)  %>
                  </small>
                </div>
                <p class="mb-1">
                  "<%= review.content %>"
                </p>
                <small>
                  <i class="fas fa-star"></i> <%= review.rating %>
                </small>
                <br>
                <small>
                  <div class="d-flex w-100 justify-content-around home-name">
                    stayed at: <%= home.name %>
                    <%= link_to home_path(home) do  %>
                      <%= cl_image_tag home.photo, class: "square-avatar" %>
                    <% end %>
                  </div>
                </small>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :photo %>
  <%= f.button :submit, "Submit Changes", class:'btn btn-primary form-actions mx-auto', style:'width:200px;' %>
<% end %>